# Generated by Django 3.1.6 on 2021-04-29 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='secondary_teachers',
            field=models.ManyToManyField(related_name='classrooms', through='teachers.TeacherMembership', to='teachers.Teacher'),
        ),
    ]
