# Generated by Django 3.1.6 on 2021-05-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_auto_20210507_2047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Responses',
            new_name='StudentResponse',
        ),
    ]
