# Generated by Django 3.1.6 on 2021-05-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_auto_20210508_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classroom', to='teachers.Student'),
        ),
    ]
