# Generated by Django 3.1.6 on 2021-05-15 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_auto_20210512_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermembership',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_membership', to='teachers.subject'),
        ),
    ]
