# Generated by Django 3.1.6 on 2021-05-15 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_auto_20210515_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmarks',
            name='student_profile',
        ),
        migrations.RemoveField(
            model_name='subjectmarks',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='teachermembership',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_memberships', to='teachers.classroom'),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='SubjectMarks',
        ),
    ]
