# Generated by Django 3.1.6 on 2021-05-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_auto_20210515_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='secondary_teachers',
        ),
        migrations.DeleteModel(
            name='TeacherMembership',
        ),
    ]
