# Generated by Django 3.1.6 on 2021-05-16 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_auto_20210515_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='classroom',
        ),
        migrations.AddField(
            model_name='notes',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='teachers.subject'),
            preserve_default=False,
        ),
    ]
