# Generated by Django 3.1.6 on 2021-05-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0016_assignment_choice_question_teachermembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='studentId',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
