# Generated by Django 3.1.6 on 2021-05-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0019_auto_20210525_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fathers_name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
