# Generated by Django 3.1.5 on 2021-06-05 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0023_auto_20210527_1715'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assignment',
            table='assignments',
        ),
        migrations.AlterModelTable(
            name='choice',
            table='choices',
        ),
        migrations.AlterModelTable(
            name='classroom',
            table='classrooms',
        ),
        migrations.AlterModelTable(
            name='classroompage',
            table='classroompages',
        ),
        migrations.AlterModelTable(
            name='document',
            table='documents',
        ),
        migrations.AlterModelTable(
            name='notes',
            table='notes',
        ),
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
        migrations.AlterModelTable(
            name='semester',
            table='semesters',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
        migrations.AlterModelTable(
            name='studentresponse',
            table='studentresponses',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subjects',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teachers',
        ),
    ]
