# Generated by Django 3.1.5 on 2021-06-07 06:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0025_gradedassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 6, 7, 6, 11, 38, 429772, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gradedassignment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='graded_assignments', to='teachers.assignment'),
        ),
    ]
