# Generated by Django 3.1.5 on 2021-06-07 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0026_auto_20210607_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 7, 49, 10, 724428, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
