# Generated by Django 3.1.5 on 2021-06-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0028_exam'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exam',
            table='exams',
        ),
    ]
