# Generated by Django 3.1.5 on 2021-06-11 09:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0029_auto_20210609_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 11, 9, 47, 25, 938666, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='finish_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
