# Generated by Django 3.1.5 on 2021-06-12 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0030_auto_20210611_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='teachers.classroom')),
            ],
            options={
                'db_table': 'TimeTable',
            },
        ),
        migrations.CreateModel(
            name='SubjectEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subjct_time', to='teachers.subject')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_entries', to='teachers.timetable')),
            ],
            options={
                'db_table': 'SubjectEntries',
            },
        ),
    ]
