# Generated by Django 3.1.5 on 2021-06-16 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0031_subjectentry_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.IntegerField()),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_result', to='teachers.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ResultRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_rows', to='teachers.manualresult')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.student')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_result', to='teachers.exam')),
            ],
        ),
    ]
