# Generated by Django 3.1.5 on 2021-06-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0032_documentresult_manualresult_resultrow'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='documentresult',
            table='document_results',
        ),
        migrations.AlterModelTable(
            name='manualresult',
            table='manual_results',
        ),
        migrations.AlterModelTable(
            name='resultrow',
            table='result_rows',
        ),
    ]
