# Generated by Django 3.1.5 on 2021-06-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0033_auto_20210616_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentresult',
            name='document',
            field=models.FileField(upload_to='result_documents/'),
        ),
    ]
