# Generated by Django 3.1.5 on 2021-06-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0034_auto_20210616_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('document', models.FileField(upload_to='ranking_documents/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_documents', to='teachers.student')),
            ],
            options={
                'db_table': 'ranking_documents',
            },
        ),
    ]
