# Generated by Django 3.1.5 on 2021-06-19 15:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0035_rankingdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingdocument',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 6, 19, 15, 57, 54, 89726, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
