# Generated by Django 3.1.5 on 2021-06-29 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0039_auto_20210627_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 6, 29, 12, 58, 9, 752386, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
