# Generated by Django 3.1.5 on 2021-07-02 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0040_documentresult_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason_title', models.CharField(max_length=355)),
                ('reason_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_file', models.FileField(upload_to='leave_request/documents')),
                ('is_pending', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.student')),
            ],
        ),
    ]
