# Generated by Django 3.1.6 on 2021-06-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210603_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='./default_profile_pic.jpg', upload_to='userprofilepics/'),
        ),
    ]
