export const LOAD_STUDENTS="LOAD_STUDENTS";
export const LOAD_CLASSROOM="LOAD_CLASSROOM";
export const REMOVE_STUDENT="REMOVE_STUDENT";
export const ADD_STUDENT="ADD_STUDENT";

// semesters
export const ADD_SEMESTER="ADD_SEMESTER";
export const REMOVE_SEMESTER="REMOVE_SEMESTER";
export const ADD_SUBJECT="ADD_SUBJECT";

export const LOAD_SEMESTERS="LOAD_SEMESTERS";
export const LOAD_TEACHERS="LOAD_TEACHERS";